import type { Metadata } from "next";
import "./globals.css";
import { MensagemProvider } from "@/data/context/MensagemContexto";
import { ProvedorAutenticacao } from "@/data/context/ContextoAutenticacao";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <MensagemProvider>
        <ProvedorAutenticacao>
          <body
            className={`antialiased`}
          >
            {children}
          </body>
        </ProvedorAutenticacao>
      </MensagemProvider>
    </html>
  );
}
